wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8080:80

db:
  image: mysql
  volumes_from:
    - dbdata
  environment:
    MYSQL_ROOT_PASSWORD: password

dbdata:
  image: mysql
  entrypoint: /bin/echo
  command: data only container for db